runtime: python311
entrypoint: gunicorn -b :$PORT myproject.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: "myproject.settings"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 16